### ISSUE TITLE
ELF binaries "listed" on your web site.

### ISSUE THREAD

**Issue by latsa** [CauldronDevelopmentLLC/camotics-web#1]
Hi Joseph, your web site at [https://cauldrondevelopment.com/](https://cauldrondevelopment.com/) looks compromised:

![image](https://user-images.githubusercontent.com/5510858/154384482-fc851e40-4535-4d25-a4f3-3f5728bc62a3.png)

**Comment by jcoffland** [comment]
Fixed.  Thanks!

**Comment by latsa** [comment]
Please click on the Sitemap link:

![image](https://user-images.githubusercontent.com/5510858/154660013-e5d64938-c953-433b-aa11-3887144941b8.png)

**Comment by jcoffland** [comment]
I think that's just cached by your browser.  Try CTRL-SHIFT-R to force a hard reload of the page.

**Comment by latsa** [comment]
It looks good now. 👍
